spring.application.name=bonus4-webflux

# --- R2DBC (reactive driver) ---
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/webflux
spring.r2dbc.username=postgres
spring.r2dbc.password=qwerty123

# --- Flyway (JDBC för migrationer) ---
spring.flyway.url=jdbc:postgresql://localhost:5432/webflux
spring.flyway.user=postgres
spring.flyway.password=qwerty123
spring.flyway.locations=classpath:db/migration
